const mongoose = require("mongoose");

/**
 * Drug — master catalog of all medicines on the platform.
 * Includes detailed attributes for composition, side effects, and reviews.
 */
const drugSchema = new mongoose.Schema(
  {
    // ── Core Identity ──────────────────────────────────────────
    name: {
      type: String,
      required: [true, "Medicine name is required"],
      unique: true,
      trim: true,
      index: true,
    },
    // Maps to 'Composition' in your DB
    composition: {
      required: [true, "Composition is required"],
      type: [String], // Array to handle ['Bevacizumab']
      default: [],
    },

    // ── Classification ─────────────────────────────────────────
    category: {
      type: String,
      required: [true, "Category is required"],
      trim: true,
      // Using your categories with "Other" as a fallback
      enum: [
        "Antibiotic", "Painkiller", "Antiviral", "Antifungal",
        "Antihistamine", "Antihypertensive", "Antidiabetic",
        "Antidepressant", "Vitamin & Supplement", "Gastrointestinal",
        "Respiratory", "Dermatological", "Ophthalmic", "Other",
      ],
      default: "Other",
    },
    dosageForm: {
      type: String,
      required: [true, "Dosage form is required"],
      enum: ["Tablet", "Capsule", "Syrup", "Injection", "Cream", "Drops", "Inhaler", "Patch", "Other"],
    },
    strength: {
      type: [String], // Array to handle ['400mg']
      default: [],
    },

    // ── Clinical Details ───────────────────────────────────────
    uses: {
      type: String, // Or [String] if you split the text later
      required: [true, "Uses is required"],
      trim: true,
    },
    sideEffects: {
      type: String,
      trim: true,
    },
    requiresPrescription: {
      type: Boolean,
      default: false,
    },

    // ── Manufacturer & Meta ────────────────────────────────────
    manufacturer: {
      type: String,
      trim: true,
      default: null,
    },
    imageUrl: {
      type: String,
      trim: true,
    },
    isbn: {
      type: String,
      unique: true,
      sparse: true, // Allows multiple null values
    },
    // ── AI Vector Field ────────────────────────────────────────
    // This stores the vector generated by Python from Composition + Uses
    embedding: {
      type: [Number],
      default: [],
      index: false, // In MongoDB Atlas, you use a Search Index instead of a standard index
    },
  },
  { timestamps: true }
);

// ── Text Index for Search ────────────────────────────────────
// This allows users to search by Name, Composition, or Use (e.g., "Cancer")
drugSchema.index(
  { 
    name: "text", 
    composition: "text", 
    uses: "text" 
  },
  { 
    weights: { 
      name: 10, 
      composition: 5, 
      uses: 2 
    },
    name: "Drug_Global_Search"
  }
);

module.exports = mongoose.model("Drug", drugSchema);